modLoader="javafml"
loaderVersion="[43,)" #forge version dep
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/iChun/Better-Than-Bunnies/issues"

[[mods]]
    modId="betterthanbunnies"
    version="${file.jarVersion}" #mandatory
    displayName="Better Than Bunnies"
    displayURL="https://ichun.me/mods/better-than-bunnies/"
    authors="iChun"
    description='''
    Better Than Bunnies! #BlameQuetzi #BlameRaj #BlameRazz
    '''

[[dependencies.betterthanbunnies]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.betterthanbunnies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
